### ISSUE TITLE
NPE in AutoCompleteSupport on OpenJDK Linux with org.GNOME.Accessibility.AtkWrapper

### ISSUE THREAD

**Issue by jbuschtoensabm** [glazedlists/glazedlists#682]
I get the following  Exception in my application.

> `java.lang.NullPointerException
	at ca.odell.glazedlists.swing.DefaultEventListModel.getSize(DefaultEventListModel.java:135)
	at javax.swing.JList$AccessibleJList$AccessibleJListChild.getComponentAtIndex(JList.java:3223)
	at javax.swing.JList$AccessibleJList$AccessibleJListChild.getCurrentAccessibleContext(JList.java:3214)
	at javax.swing.JList$AccessibleJList$AccessibleJListChild.getAccessibleRole(JList.java:3293)
	at org.GNOME.Accessibility.AtkWrapper$5.propertyChange(AtkWrapper.java:595)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at javax.accessibility.AccessibleContext.firePropertyChange(AccessibleContext.java:766)
	at javax.swing.JComboBox$AccessibleJComboBox$AccessibleJComboBoxListSelectionListener.valueChanged(JComboBox.java:1771)
	at javax.swing.JList.fireSelectionValueChanged(JList.java:1802)
	at javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1816)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
	at javax.swing.JList.setSelectedIndex(JList.java:2216)
	at javax.swing.plaf.basic.BasicComboPopup.setListSelection(BasicComboPopup.java:1186)
	at javax.swing.plaf.basic.BasicComboPopup.access$300(BasicComboPopup.java:65)
	at javax.swing.plaf.basic.BasicComboPopup$Handler.itemStateChanged(BasicComboPopup.java:1015)
	at javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1223)
	at javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1280)
	at javax.swing.JComboBox.contentsChanged(JComboBox.java:1330)
	at ca.odell.glazedlists.swing.DefaultEventListModel.fireListDataEvent(DefaultEventListModel.java:171)
	at ca.odell.glazedlists.swing.EventComboBoxModel.setSelectedItem(EventComboBoxModel.java:61)
	at ca.odell.glazedlists.swing.AutoCompleteSupport$AutoCompleteComboBoxModel.setSelectedItem(AutoCompleteSupport.java:1337)
	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:576)
	at de.abm.formgen.inspector.InspectorStringWithAutocomplete.setData(InspectorStringWithAutocomplete.java:130)
`

I can reliably provoke this in my application. But I wasn't able to wirte a simple example that produces this error. I can reproduce this with Open JDK 8 and 11 on Linux. I can not reproduce this with Oracles Java 8 JRE on Linux or with Open JDK 8 on Windows.

The exception does not occur when I edit /etc/java-8-openjdk/accessibility.properties and comment out the line

> assistive_technologies=org.GNOME.Accessibility.AtkWrapper

Looking at it with a debugger, I see that source is null in 
>      public int getSize() {
>         source.getReadWriteLock().readLock().lock();
>         try {
>             return source.size();
>        } finally {
>           source.getReadWriteLock().readLock().unlock();
>         }
>      }

The application code is:

>     private JComboBox<String> cbText;
>     private AutoCompleteSupport<String> autocomplete;
>    
>      protected void setData(final JComponent obj, final Object data) {
>           autocomplete.uninstall();
>           autocomplete = AutoCompleteSupport.install(cbText, GlazedLists.eventList(getAutocompleteValues((T) data)));
>           cbText.setSelectedItem(wrapperToString((T) data));
>     }

The exception occurs on the 5th time setData is called, and after that every time it gets called.

**Comment by hbrands** [comment]
It's hard to say what's going on without a reproducible testcase.
Also, I'm not familiar with the AtkWrapper and I have no immediate access to a Linux system.

Before digging deeper:
Does it help as a workaround, if you clear the selection of the combobox in your setData-method before uninstalling the autocomplete support?

It seems to me, that the AccessibleJComboBox and it's components hold a reference to an old list model (DefaultEventListModel in this case) that is already disposed. That's why the source is null.

I think there might be a problem in the constructor of javax.swing.JList$AccessibleJList$AccessibleJListChild:
It saves a reference to the ListModel from the JList. But what if the model is replaced in JList in the meantime?  Then AccessibleJListChild holds a dangling reference which might be the case here.

**Comment by jbuschtoensabm** [comment]
The following still produces the same error

```
    protected void setData(final JComponent obj, final Object data) {
        log().info("setData " + data);
        cbText.setSelectedItem(null);
        autocomplete.uninstall();
        autocomplete = AutoCompleteSupport.install(cbText, GlazedLists.eventList(getAutocompleteValues((T) data)));
        cbText.setSelectedItem(wrapperToString((T) data));
    }
```
