### ISSUE TITLE
Unexpected type exception for parameterized classes

### ISSUE THREAD

**Issue by mpulchny** [glazedlists/glazedlists#683]
Hi,

I get following exception in my application:

> `Unexpected type. Expected: java.lang.reflect.ParameterizedType, got: sun.reflect.generics.reflectiveObjects.TypeVariableImpl, for type literal: E.
java.lang.AssertionError: Unexpected type. Expected: java.lang.reflect.ParameterizedType, got: sun.reflect.generics.reflectiveObjects.TypeVariableImpl, for type literal: E.
	at ca.odell.glazedlists.impl.reflect.MoreTypes.unexpectedType(MoreTypes.java:121)
	at ca.odell.glazedlists.impl.reflect.MoreTypes.getRawType(MoreTypes.java:113)
	at ca.odell.glazedlists.impl.reflect.TypeLiteral.<init>(TypeLiteral.java:61)
	at ca.odell.glazedlists.impl.reflect.TypeLiteral.get(TypeLiteral.java:98)
	at ca.odell.glazedlists.impl.reflect.TypeLiteral.resolve(TypeLiteral.java:122)
	at ca.odell.glazedlists.impl.reflect.TypeLiteral.getReturnType(TypeLiteral.java:200)
	at ca.odell.glazedlists.impl.reflect.J2SE50ReturnTypeResolver.getReturnType(J2SE50ReturnTypeResolver.java:17)
	at ca.odell.glazedlists.impl.beans.BeanProperty.<init>(BeanProperty.java:84)
	at myproject.BeanPropertyMatcherEditor.(BeanPropertyMatcherEditor.java:37)
...`

In this place there is:
`      BeanProperty beanProperty = new BeanProperty(beanClass, propertyName, true, false);
`

and the issue occurs when the code is invoked for generic class.

I was able to reproduce the issue with following test:
[https://github.com/mpulchny/glazedlists/commit/5eaff8738ff6db8f6fbccf629488737502e68d52#diff-a226fd17dad3e13cde24dbcaa7106a4bR161](https://github.com/mpulchny/glazedlists/commit/5eaff8738ff6db8f6fbccf629488737502e68d52#diff-a226fd17dad3e13cde24dbcaa7106a4bR161)

And even fix it by updating MoreTypes with some changes from latest Guice version (in the same commit), but I don't know if it's a good way to go.

Can this change be added to glazedlists code?

**Comment by hbrands** [comment]
@mpulchny Looks good to me. I just committed your changes. Thanks!
